import { describe, expect, it } from "vitest";
import { AppError, ShopifyUserError, type Product } from "../app/domain";
import { GraphqlAdminClient } from "../app/shopify/graphql";
import { MockShopifyAdminClient, fixtureProducts } from "../app/shopify/mock";
import { MemoryOperationsStore } from "../app/store/memory";
import { refreshProductsByCursor, requestInitialSync } from "../app/services/sync";
import { receiveWebhook } from "../app/services/webhooks";
import { featureProduct } from "../app/services/merchandising";
import { runNextJob } from "../app/jobs/runner";

const shop = "test-shop.myshopify.com";
const policy = { attempts: 3, baseDelayMs: 0, sleep: async () => {} };
async function setup() { const store = new MemoryOperationsStore(); const client = new MockShopifyAdminClient(policy); await store.install(shop, "read_products,write_products,read_orders"); return { store, client }; }
async function drain(store: MemoryOperationsStore, client: MockShopifyAdminClient) { for (let i = 0; i < 12; i++) await runNextJob(store, async () => client, new Date(Date.now() + i * 6000)); }

describe("merchant operations", () => {
  it("paginates Shopify products and mirrors every page", async () => { const { store, client } = await setup(); expect(await refreshProductsByCursor(store, client, shop, 2)).toBe(3); expect((await store.products(shop)).map((p) => p.title)).toHaveLength(3); });
  it("creates durable bulk jobs, waits, then ingests Shopify JSONL through the mirror service", async () => { const { store, client } = await setup(); const jobs = await requestInitialSync(store, shop); expect(jobs).toHaveLength(2); await runNextJob(store, async () => client); expect(store.jobs.get(jobs[0]!.id)?.status).toBe("WAITING"); await drain(store, client); const dashboard = await store.dashboard(shop); expect(dashboard.productCount).toBe(3); expect(dashboard.orderCount).toBe(2); expect(dashboard.jobs.every((job) => job.status === "COMPLETED")).toBe(true); });
  it("deduplicates a repeated webhook delivery", async () => { const { store, client } = await setup(); await store.setSyncEnabled(shop, true); const input = { id: "delivery-1", shopDomain: shop, topic: "PRODUCTS_UPDATE", resourceId: fixtureProducts[0]!.id }; expect(await receiveWebhook(store, input)).toBe(true); expect(await receiveWebhook(store, input)).toBe(false); await drain(store, client); expect(store.deliveries.size).toBe(1); expect(await store.product(shop, fixtureProducts[0]!.id)).not.toBeNull(); });
  it("reconciles out-of-order update webhooks against current Shopify state", async () => { const { store, client } = await setup(); await store.setSyncEnabled(shop, true); const newer: Product = { ...fixtureProducts[0]!, title: "Latest title", updatedAt: "2026-09-20T00:00:00.000Z" }; client.updateProduct(newer); await receiveWebhook(store, { id: "new", shopDomain: shop, topic: "PRODUCTS_UPDATE", resourceId: newer.id }); await receiveWebhook(store, { id: "old", shopDomain: shop, topic: "PRODUCTS_CREATE", resourceId: newer.id }); await drain(store, client); expect((await store.product(shop, newer.id))?.title).toBe("Latest title"); });
  it("handles a product delete only after checking current state", async () => { const { store, client } = await setup(); await store.setSyncEnabled(shop, true); await store.upsertProducts(shop, [fixtureProducts[0]!]); client.deleteProduct(fixtureProducts[0]!.id); await receiveWebhook(store, { id: "delete", shopDomain: shop, topic: "PRODUCTS_DELETE", resourceId: fixtureProducts[0]!.id }); await drain(store, client); expect(await store.product(shop, fixtureProducts[0]!.id)).toBeNull(); });
  it("refreshes an order from current Shopify state without customer PII", async () => { const { store, client } = await setup(); await store.setSyncEnabled(shop, true); const old = (await client.getOrder("gid://shopify/Order/201"))!; client.updateOrder({ ...old, displayFulfillmentStatus: "FULFILLED", updatedAt: "2026-09-21T00:00:00.000Z" }); await receiveWebhook(store, { id: "order-update", shopDomain: shop, topic: "ORDERS_UPDATED", resourceId: old.id }); await drain(store, client); expect((await store.orders(shop))[0]?.displayFulfillmentStatus).toBe("FULFILLED"); expect(JSON.stringify(await store.orders(shop))).not.toContain("email"); });
  it("surfaces mutation userErrors without updating the mirror or audit", async () => { const { store, client } = await setup(); await store.upsertProducts(shop, [fixtureProducts[0]!]); client.userErrorOnce(); await expect(featureProduct(store, client, shop, fixtureProducts[0]!.id)).rejects.toBeInstanceOf(ShopifyUserError); expect(store.audits).toHaveLength(0); });
  it("retries throttling and temporary HTTP failure", async () => { const { client } = await setup(); client.throttleOnce(); expect((await client.listProducts(1)).items).toHaveLength(1); client.failOnce(); expect((await client.listProducts(1)).items).toHaveLength(1); });
  it("does not retry permanent top-level GraphQL errors", async () => { let calls = 0; const client = new GraphqlAdminClient(async () => { calls++; return Response.json({ errors: [{ message: "Access denied", extensions: { code: "ACCESS_DENIED" } }] }); }, fetch, policy); await expect(client.listProducts(1)).rejects.toMatchObject({ code: "SHOPIFY_GRAPHQL" }); expect(calls).toBe(1); });
  it("does not retry permanent job errors forever", async () => { const { store, client } = await setup(); await store.enqueue(shop, "BULK_PRODUCTS"); const broken = new GraphqlAdminClient(async () => Response.json({ errors: [{ message: "Invalid query" }] }), fetch, policy); await runNextJob(store, async () => broken); expect([...store.jobs.values()][0]?.status).toBe("FAILED"); expect([...store.jobs.values()][0]?.attempts).toBe(1); void client; });
  it("marks uninstall inactive and blocks further Shopify calls", async () => { const { store, client } = await setup(); await receiveWebhook(store, { id: "uninstall", shopDomain: shop, topic: "APP_UNINSTALLED", resourceId: null }); await drain(store, client); expect((await store.shop(shop))?.installationStatus).toBe("UNINSTALLED"); await expect(requestInitialSync(store, shop)).rejects.toBeInstanceOf(AppError); });
  it("records privacy requests without customer PII and redacts all shop data", async () => { const { store, client } = await setup(); await store.upsertProducts(shop, [fixtureProducts[0]!]); await receiveWebhook(store, { id: "customer", shopDomain: shop, topic: "CUSTOMERS_REDACT", resourceId: null }); await drain(store, client); expect(store.audits.map((item) => item.action)).toContain("CUSTOMER_REDACT_NO_PII"); await receiveWebhook(store, { id: "shop-redact", shopDomain: shop, topic: "SHOP_REDACT", resourceId: null }); await drain(store, client); expect(await store.shop(shop)).toBeNull(); expect(await store.products(shop)).toHaveLength(0); });
  it("keeps a pending privacy redaction job when uninstall cancels other work", async () => { const { store, client } = await setup(); await receiveWebhook(store, { id: "uninstall-first", shopDomain: shop, topic: "APP_UNINSTALLED", resourceId: null }); await receiveWebhook(store, { id: "redact-later", shopDomain: shop, topic: "SHOP_REDACT", resourceId: null }); await drain(store, client); expect(await store.shop(shop)).toBeNull(); });
});
